@ProductApi_HostAddress = http://localhost:5125

### Create a product
POST {{ProductApi_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Test Product",
  "status": 1,
  "stock": 100,
  "description": "Test product description",
  "price": 99.99
}

### Get a product by ID
GET {{ProductApi_HostAddress}}/api/products/1
Accept: application/json

### Update a product
PUT {{ProductApi_HostAddress}}/api/products/1
Content-Type: application/json

{
  "productId": 1,
  "name": "Updated Product",
  "status": 1,
  "stock": 50,
  "description": "Updated description",
  "price": 89.99
}
